# Generated by scripts/homebrew_bottles.py from the v0.1.0-alpha.37 release assets. Do not edit by hand; regenerate instead.
class Knit < Formula
  desc "Local-first CLI for coordinating cross-repo feature bundles"
  homepage "https://github.com/knit-cli/knit"
  version "0.1.0-alpha.37"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.37/knit-v0.1.0-alpha.37-aarch64-apple-darwin.tar.gz"
      sha256 "fe0250ae6b0d159c3ce1e19c97d4c07900914e11863582356336d331a96970be"
    else
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.37/knit-v0.1.0-alpha.37-x86_64-apple-darwin.tar.gz"
      sha256 "9fa6dc88a51c680dc29a70f16a8a1cbbef518b4972ede2751a6c01f6d6316673"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.37/knit-v0.1.0-alpha.37-aarch64-unknown-linux-musl.tar.gz"
      sha256 "aeccf4627bae285651c5b5393f5a14d5f56a9854435c16ff127cead1e8342c93"
    else
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.37/knit-v0.1.0-alpha.37-x86_64-unknown-linux-musl.tar.gz"
      sha256 "289354e600c1b588684447d926f09af4a47047e7c6d5289fc5c286f962001d89"
    end
  end

  bottle do
    root_url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.37"
    sha256 cellar: :any_skip_relocation, arm64_big_sur: "1eb3e1741fb25b6113e4802c097ef1e1895becc24c7a5f893e82e319e975c467"
    sha256 cellar: :any_skip_relocation, big_sur: "d5c24bb6f39c449ca6348a1da3c5f4b6d467a70e31e1bb3d64f3b99bcd1b14c1"
    sha256 cellar: :any_skip_relocation, arm64_linux: "e197441c3c578dc00625968516ca70366915efe0dee7191920d81e2f32bfc59c"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "733899cd4462ed219cb96703359aabfaa3d5c8544409b887d0a5dd2a89c54cde"
  end

  def install
    bin.install "knit"
  end

  test do
    assert_match "knit", shell_output("#{bin}/knit --version")
  end
end
