# Generated by scripts/homebrew_bottles.py from the v0.1.0-alpha.44 release assets. Do not edit by hand; regenerate instead.
class Knit < Formula
  desc "Local-first CLI for coordinating cross-repo feature bundles"
  homepage "https://github.com/knit-cli/knit"
  version "0.1.0-alpha.44"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.44/knit-v0.1.0-alpha.44-aarch64-apple-darwin.tar.gz"
      sha256 "5518e2b3668f635665fe2ffa5d298b51d5f1d3ed61b5aff75d3bcac690163f89"
    else
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.44/knit-v0.1.0-alpha.44-x86_64-apple-darwin.tar.gz"
      sha256 "cf6f6120be1a7a296f50397115f66f02c82cb5cb3990841b75c52162d6156efa"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.44/knit-v0.1.0-alpha.44-aarch64-unknown-linux-musl.tar.gz"
      sha256 "6c6f1b785fe76ffed9faffa79bc0c02ac789ee26a5dd0c9ac6140f7018ff08d7"
    else
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.44/knit-v0.1.0-alpha.44-x86_64-unknown-linux-musl.tar.gz"
      sha256 "1a54d82fb904aa3e75361e87d83dbe068d6b353cd93bfc3d5737cbe0cf2ca1d3"
    end
  end

  bottle do
    root_url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.44"
    sha256 cellar: :any_skip_relocation, arm64_big_sur: "779f8cefbf7ff7fbad30359813f14e7c15ae4042e9541c606a2c20b6dc128401"
    sha256 cellar: :any_skip_relocation, big_sur: "4a10fc8173b219088e728dc9264faaa28c98c86e575693133c2f58769c81522f"
    sha256 cellar: :any_skip_relocation, arm64_linux: "0af153af6e0949dd6d77155c5fb6c5331d4e3bbd457b3edb7ec27a8db7c40ec1"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "80a671f5e2a407df9e9e2b4e1887ae49b3b23cc9b0ad333fa68994cf25564a06"
  end

  def install
    bin.install "knit"
  end

  test do
    assert_match "knit", shell_output("#{bin}/knit --version")
  end
end
