# Generated by scripts/homebrew_bottles.py from the v0.1.0-alpha.40 release assets. Do not edit by hand; regenerate instead.
class Knit < Formula
  desc "Local-first CLI for coordinating cross-repo feature bundles"
  homepage "https://github.com/knit-cli/knit"
  version "0.1.0-alpha.40"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.40/knit-v0.1.0-alpha.40-aarch64-apple-darwin.tar.gz"
      sha256 "f35478bf22b2514b03332de7fde01b7b5b4fa67a938c785a867fc4c9bfa64199"
    else
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.40/knit-v0.1.0-alpha.40-x86_64-apple-darwin.tar.gz"
      sha256 "3ed897d9ea6619bce88b5d8d12afe72f0754a488318ea943ca1a06a88b7b8ac0"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.40/knit-v0.1.0-alpha.40-aarch64-unknown-linux-musl.tar.gz"
      sha256 "46c92347cec3503e08387425e3e67cd41ba4e80c8fd06c16e83fbc2f184a0581"
    else
      url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.40/knit-v0.1.0-alpha.40-x86_64-unknown-linux-musl.tar.gz"
      sha256 "3ba9f735c07dd6619e1d99b1cc49724e027ef06298ca38d2180425ba8975b3bb"
    end
  end

  bottle do
    root_url "https://github.com/knit-cli/knit/releases/download/v0.1.0-alpha.40"
    sha256 cellar: :any_skip_relocation, arm64_big_sur: "4020034462889bd548365ddcf4e45be0b3a8386eb0c4fc9b104682d9f888b038"
    sha256 cellar: :any_skip_relocation, big_sur: "04f8dc1e232aa37847c9bd1e2bea758133c7241e4a2c0b2ef3cf064413e6677d"
    sha256 cellar: :any_skip_relocation, arm64_linux: "8773e36444b558299161e6f9bc48c4de7a415ba5f325d1c969a39ef033b1eb83"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "70aa5ba59ac39b358fb2dc6c201610ec70e9b15ae26c798e974798b31e78de93"
  end

  def install
    bin.install "knit"
  end

  test do
    assert_match "knit", shell_output("#{bin}/knit --version")
  end
end
